### ISSUE TITLE
Diagnoses button doesn't do anything

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-backend#16]
## Describe the bug
-> See picture self-explainatory

## Screenshots
![rert](https://user-images.githubusercontent.com/55558015/125457847-8f9eded2-c14c-4901-8ec5-f0a8776e59b0.PNG)

**Comment by alanvonlanthen** [comment]
Fixed on 14.07.2021

**Comment by jouz56k** [comment]
Partially fixed
Now we can go to Diagnoses section, but the step before stay clicked
-> See picture to understand what I mean
![sdfsdf](https://user-images.githubusercontent.com/55558015/125913695-9bf99101-86f4-4fb1-879e-7da8f1876db3.PNG)
![sdfsdfsdf](https://user-images.githubusercontent.com/55558015/125913708-c6d04baf-8aee-482d-8d2b-b1821c15bb3f.PNG)

**Comment by jouz56k** [comment]
Nice -> Fully fixed I close this one
